{
 "title": "Scale dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "exchange-api-1, exchange-api-2, exchange-api-3, exchange-cadvisor-1, exchange-grafana-1, exchange-graphite-1,  exchange-nginx-1, exchange_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Currency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Volume by Currency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.arVault.*.exchange.volume.*, 5)"
      }
     ]
    },
    {
     "title": "Global Net Volume by currency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "target": "aliasByNode(sumSeries(stats_counts.arVault.*.exchange.net.ARS), 5)"
      },
      {
       "target": "aliasByNode(sumSeries(stats_counts.arVault.*.exchange.net.USD), 5)"
      }
     ]
    },
    {
     "title": "Volume by Currency (by Container)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.arVault.$container.exchange.volume.*, 5)"
      }
     ]
    },
    {
     "title": "Net Volume by Currency (by Container)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.arVault.$container.exchange.net.*, 5)"
      }
     ]
    }
   ]
  },
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Succes vs Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Success (200 OK)')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$server.codes.4*, stats.gauges.$server.codes.5*, stats.gauges.$server.errors.*), 'Error')"
    }
   ]
  },
  {
   "title": "Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$server.scenarioDuration.p99, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.$server.scenarioDuration.p95, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.$server.scenarioDuration.p90, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.$server.scenarioDuration.median, 4)"
    }
   ]
  },
  {
   "title": "Global Real Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "alias(scaleToSeconds(sumSeries(stats.gauges.$server.codes.*, stats.gauges.$server.errors.*), 1), 'RPS Client (Artillery)')"
    },
    {
     "target": "alias(sumSeries(stats_counts.arVault.*.exchange.processed), 'RPS Server (Global)')"
    }
   ]
  },
  { "title": "Stats by Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Throughput (RPS) by $container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "aliasByNode(stats_counts.arVault.$container.exchange.processed, 2)"
    }
   ]
  },
  {
   "title": "Server Latency (by $container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.timers.arVault.$container.response_time_exchange.upper_99, 'p99')"
    },
    {
     "target": "alias(stats.timers.arVault.$container.response_time_exchange.upper_95, 'p95')"
    },
    {
     "target": "alias(stats.timers.arVault.$container.response_time_exchange.upper_90, 'p90')"
    },
    {
     "target": "alias(stats.timers.arVault.$container.response_time_exchange.median, 'median')"
    }
   ]
  },
  {
   "title": "Succes vs Errors Server side (by $container )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 5, "y": 27 },
   "targets": [
    {
     "target": "alias(stats_counts.arVault.$container.codes.2xx, 'Success (2xx)')"
    },
    {
     "target": "alias(sumSeries(stats_counts.arVault.$container.codes.4xx, stats_counts.arVault.$container.codes.5xx), 'Error (4xx-5xx)')"
    }
   ]
  },
  {
   "title": "Total Cpu % (by $container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"$container\"}[5m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage (by $container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"$container\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Total Cpu %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"exchange-api-2\"}[5m])",
     "legendFormat": "{{name}} "
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"exchange-api-3\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[5m]))",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!=\"\"})",
     "legendFormat": "{{name}} "
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"exchange-api-2\"}",
     "legendFormat": "{{name}} "
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"exchange-api-3\"}",
     "legendFormat": "{{name}} "
    }
   ]
  }
 ]
}